version: '3'

services:
  finanzas_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finanzasApp
    ports:
      - "3500:80"
    depends_on:
      - database

  database:
    image: mariadb
    container_name: finanzasBD
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finanzas
      MYSQL_USER: finanzas
      MYSQL_PASSWORD: finanzas
    ports:
      - "33060:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./others/bd.sql:/docker-entrypoint-initdb.d/bd.sql

volumes:
  db-volume:
